import React, { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { FileText, Download, Plus, Filter, Eye, Trash2 } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Select } from '../components/ui/Select';
import { Badge } from '../components/ui/Badge';
import { DataTable } from '../components/ui/DataTable';
import { Input } from '../components/ui/Input';
import { Modal } from '../components/ui/Modal';
import { reportsService } from '../services/api';
import { downloadJson } from '../utils/downloadJson';

type ReportListRow = {
  id: number;
  name: string;
  program: string;
  date: string;
  generatedBy: string;
  status: string;
};

export function ReportsPage() {
  const [showGenerateReport, setShowGenerateReport] = useState(false);
  const [snapshot, setSnapshot] = useState<{
    enrollments: number;
    docs: number;
    assessments: number;
    generatedAt: string;
  } | null>(null);

  useEffect(() => {
    reportsService
      .getSetaSnapshot()
      .then((res) => setSnapshot(res.data))
      .catch(() => toast.error('Could not load SETA snapshot'));
  }, []);

  const reports: ReportListRow[] = snapshot
    ? [
        {
          id: 1,
          name: 'SETA operational snapshot',
          program: 'All programmes',
          date: new Date(snapshot.generatedAt).toLocaleString(),
          generatedBy: 'API',
          status: 'Completed',
        },
      ]
    : [];

  const downloadSnapshot = async () => {
    try {
      const res = await reportsService.getSetaSnapshot();
      downloadJson('seta-snapshot.json', res.data);
      toast.success('Report downloaded');
    } catch {
      toast.error('Download failed');
    }
  };

  const previewSnapshot = async () => {
    try {
      const res = await reportsService.getSetaSnapshot();
      window.open(
        `data:application/json,${encodeURIComponent(JSON.stringify(res.data, null, 2))}`,
        '_blank',
        'noopener',
      );
    } catch {
      toast.error('Could not open preview');
    }
  };

  const columns = [
  {
    header: 'REPORT NAME',
    accessorKey: 'name' as const,
    cell: (row: ReportListRow) =>
    <div>
          <div className="font-medium text-gray-900">{row.name}</div>
          <div className="text-xs text-gray-500">{row.program}</div>
        </div>

  },
  {
    header: 'GENERATION DATE',
    accessorKey: 'date' as const
  },
  {
    header: 'GENERATED BY',
    accessorKey: 'generatedBy' as const
  },
  {
    header: 'STATUS',
    accessorKey: 'status' as const,
    cell: (row: ReportListRow) =>
    <Badge variant={row.status === 'Completed' ? 'success' : 'info'}>
          {row.status}
        </Badge>

  },
  {
    header: 'ACTIONS',
    accessorKey: 'id' as const,
    cell: () =>
    <div className="flex space-x-2 text-gray-400">
          <button
        className="hover:text-brand-blue"
        onClick={() => void previewSnapshot()}>
        
            <Eye className="h-4 w-4" />
          </button>
          <button
        className="hover:text-brand-blue"
        onClick={() => void downloadSnapshot()}>
        
            <Download className="h-4 w-4" />
          </button>
          <button
        className="hover:text-red-500"
        disabled
        title="Delete not supported">
        
            <Trash2 className="h-4 w-4" />
          </button>
        </div>

  }];

  const handleGenerateReport = async () => {
    try {
      const res = await reportsService.getSetaSnapshot();
      setSnapshot(res.data);
      downloadJson('seta-report.json', res.data);
      toast.success('Report generated successfully');
      setShowGenerateReport(false);
    } catch {
      toast.error('Could not generate report');
    }
  };
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">SETA Reports</h1>
          <p className="text-sm text-gray-500">
            Generate and view SETA-aligned reports for your learnership
            programs.
          </p>
        </div>
        <Button
          leftIcon={<Plus className="h-4 w-4" />}
          onClick={() => setShowGenerateReport(true)}>
          
          Generate New Report
        </Button>
      </div>

      <Card title="Report Filters">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
          <Select
            label="Qualification"
            options={[
            {
              value: 'all',
              label: 'All Qualifications'
            }]
            } />
          
          <Select
            label="Learnership"
            options={[
            {
              value: 'all',
              label: 'All Learnerships'
            }]
            } />
          
          <Select
            label="Learner Group"
            options={[
            {
              value: 'all',
              label: 'All Groups'
            }]
            } />
          
          <Input
            label="Reporting Period"
            type="date"
            placeholder="mm/dd/yyyy" />
          
        </div>
        <div className="flex justify-end space-x-3">
          <Button variant="outline" onClick={() => setShowGenerateReport(false)}>
            Reset Filters
          </Button>
          <Button
            variant="secondary"
            leftIcon={<Filter className="h-4 w-4" />}
            disabled
            title="Configure filters in the form above">
          </Button>
        </div>
      </Card>

      <Card
        title="Generated Reports"
        action={
        <div className="flex space-x-3 text-sm text-gray-500">
            <span
            className="flex items-center cursor-pointer hover:text-gray-700"
            onClick={() => void downloadSnapshot()}>
            
              <FileText className="h-4 w-4 mr-1" /> PDF
            </span>
            <span
            className="flex items-center cursor-pointer hover:text-gray-700"
            onClick={() => void downloadSnapshot()}>
            
              <FileText className="h-4 w-4 mr-1" /> CSV
            </span>
          </div>
        }>
        
        <DataTable data={reports} columns={columns} keyField="id" />
      </Card>

      <Modal
        isOpen={showGenerateReport}
        onClose={() => setShowGenerateReport(false)}
        title="Generate New Report">
        
        <div className="space-y-4">
          <Select
            label="Report Type"
            options={[
            {
              value: 'progress',
              label: 'Progress Report'
            },
            {
              value: 'enrolment',
              label: 'Enrolment Report'
            },
            {
              value: 'assessment',
              label: 'Assessment Report'
            },
            {
              value: 'compliance',
              label: 'Compliance Report'
            }]
            } />
          
          <Select
            label="Programme"
            options={[
            {
              value: 'it',
              label: 'IT Skills Program'
            },
            {
              value: 'business',
              label: 'Business Administration'
            }]
            } />
          
          <Select
            label="Reporting Period"
            options={[
            {
              value: 'q1',
              label: 'Q1 (Jan - Mar)'
            },
            {
              value: 'q2',
              label: 'Q2 (Apr - Jun)'
            },
            {
              value: 'q3',
              label: 'Q3 (Jul - Sep)'
            },
            {
              value: 'q4',
              label: 'Q4 (Oct - Dec)'
            }]
            } />
          
          <Select
            label="Format"
            options={[
            {
              value: 'pdf',
              label: 'PDF Document'
            },
            {
              value: 'csv',
              label: 'CSV Data'
            },
            {
              value: 'excel',
              label: 'Excel Spreadsheet'
            }]
            } />
          
          <div className="flex justify-end space-x-3 pt-4">
            <Button
              variant="ghost"
              onClick={() => setShowGenerateReport(false)}>
              
              Cancel
            </Button>
            <Button onClick={handleGenerateReport}>Generate Report</Button>
          </div>
        </div>
      </Modal>
    </div>);

}